source 'https://rubygems.org'

ruby '2.1.3'

gem 'rails',                      '4.1.8'
gem 'bcrypt',                     '3.1.7'
gem 'bootstrap-sass',             '3.2.0.0'

gem 'sass-rails',                 '~> 4.0.5'
gem 'uglifier',                   '>= 1.3.0'
gem 'coffee-rails',               '~> 4.0.0'
gem 'jquery-rails',               '3.1.2'
gem 'turbolinks',                 '2.5.3'
gem 'jbuilder',                   '~> 2.0'
gem 'sdoc', '~> 0.4.0',           group: :doc
gem 'spring', '1.2.0',            group: :development


group :development, :test do
  gem 'sqlite3',                  '1.3.10'
  gem 'rspec-rails',              '2.13.1'
end


group :test do
  gem 'minitest-reporters', '1.0.5'
  gem 'selenium-webdriver', '2.35.1'
  gem 'capybara', '2.1.0'
  gem 'factory_girl_rails', '4.2.0'
  gem 'mocha'
end

group :production do
  gem 'pg',                       '0.17.1'
  gem 'rails_12factor',           '0.0.3'
end


